### ISSUE TITLE
Apollo todo list after the aussie apollo workshop

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/training-material#3069]
- [ ] Let's update the apollo slide deck to give a bit more time to moving around, controls, etc.
- [ ] We need to add sixpack to the GTN tutorial datasets, that'll give a better demo in some places, and we should add sections on blat/sequence search track/when you'd use either of those
- [ ] Apollo advanced? Cover some more advanced aspects like report tab and management of organisms?

**Comment by abretaud** [comment]
Thanks for writing it here!
While preparing the funannotate tutorial, I also think we could have a nice learning path with a real eukaryote genome: [PacBio QC tutorial](https://github.com/galaxyproject/training-material/pull/3006) -> [assembly with flye](https://github.com/galaxyproject/training-material/pull/3058) -> [annotation with funannotate](https://github.com/galaxyproject/training-material/pull/2985) -> manual curation with apollo

**Comment by hexylena** [comment]
Yes! That's a fantastic plan, great plan
