### ISSUE TITLE
Conda advanced topics TODO

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/training-material#375]
- [ ] Jinja templates inside of `meta.yaml`: https://conda.io/docs/building/meta-yaml.html#templating-with-jinja
- [ ] tests: in BioConda keep them simple, just check if installation was successful
- [ ] use tarballs: how to get tarballs from GitHub/Mercurial: https://bioconda.github.io/guidelines.html#stable-urls
- [ ] preprocessing selector: https://conda.io/docs/building/meta-yaml.html#preprocessing-selectors
- [ ] the entire concept of "You provide us with one recipe, but we build 8 different packages out of it" (e.g. 4 python packages for Linux, 4 for OS X)
- [ ] library pinning: how and why: https://bioconda.github.io/guidelines.html#c-c

**Comment by nsoranzo** [comment]
Requested by @jmchilton, most suggestions from @bgruening.
